export function fetchRegion() {

    const factionsData = {
      factions: [
      {
        type: "faction",
        name: "Bandle City",
        slug: "bandle-city",
        image: {
          title: "bandle-city-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/blt57ea8bb74f8733f3/60ee0b95bc44fe5b48ba2a02/bandle-city_splash.jpg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 0,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "Bilgewater",
        slug: "bilgewater",
        image: {
          title: "bilgewater-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/blt8efd86a20a7fc6ca/60ee0bd126ed9249f5484b8c/bilgewater_splash.jpg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 1,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "Demacia",
        slug: "demacia",
        image: {
          title: "demacia-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/bltd170f10ccce6ba7e/614cc12077d06a0c9835f862/demacia_splash.jpeg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 2,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "Ionia",
        slug: "ionia",
        image: {
          title: "ionia-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/bltcea170f820e544c5/60ee0e19a471a34acb2c1f66/ionia-01.jpg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 3,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "Ixtal",
        slug: "ixtal",
        image: {
          title: "ixtal-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/blt9a01601bbdff5c4a/60ee0e385fbfcb5e848229a5/ixtal_splash.jpg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 4,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "Noxus",
        slug: "noxus",
        image: {
          title: "noxus-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/blt9d0c487b98ba6b42/60ee0ffb975ffd4ff25ec2f5/noxus_splash.jpg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 5,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "Piltover",
        slug: "piltover",
        image: {
          title: "piltover-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/blt5c307209ccbe2470/60ee10d06610ed4d42bc222e/piltover_splash.jpg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 6,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "Shadow Isles",
        slug: "shadow-isles",
        image: {
          title: "shadow-isles-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/bltd9cec6dc7ca0fc48/60ee11d22f7fa122fd574a11/shadow-isles_splash.jpg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 7,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "Shurima",
        slug: "shurima",
        image: {
          title: "shurima-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/blt5924e500520eabd9/60ee11fb94d70a1ef3123825/shurima_splash.jpg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 8,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "Targon",
        slug: "mount-targon",
        image: {
          title: "mount-targon-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/blt1ab39bfee4a3057d/60ee0f894fba2021cde587f6/mount-targon_splash.jpg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 9,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "The Freljord",
        slug: "freljord",
        image: {
          title: "freljord-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/bltc15ba510f02e7e45/60ee0d9185b042284396138b/freljord_splash.jpg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 10,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "The Void",
        slug: "void",
        image: {
          title: "void-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/blt4754fc6a91233824/60ee139d5397524ead38918f/void-an-unknowable-power.jpg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 11,
        "associated-champions": null,
      },
      {
        type: "faction",
        name: "Zaun",
        slug: "zaun",
        image: {
          title: "zaun-splash",
          subtitle: "",
          description: "",
          uri: "https://images.contentstack.io/v3/assets/blt187521ff0727be24/blt3d038a51072c6d5a/614cc18164c8007a9bdec0e2/zaun_splash.jpeg",
          encoding: "image/jpeg",
          width: null,
          height: null,
          x: null,
          y: null,
          "featured-champions": [],
        },
        echelon: 12,
        "associated-champions": null,
      },
    ],
  };

  return factionsData;
}
